# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
    ]
